language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-28
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - ".+"
branches:
  except:
    - /^v[0-9]+/
before_install:
- yes | sdkmanager "platforms;android-28"
script:
- chmod +x gradlew
- "./gradlew testDebugUnitTest assembleDebug"
notifications:
  email: false
sudo: false
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache
